### ISSUE TITLE
网页中teatarea编辑区域不能适应浏览器的高度

### ISSUE THREAD

**Issue by ueumd** [Houfeng/mditor#23]
网页中teatarea编辑区域不能适应浏览器的高度

**Comment by Houfeng** [comment]
@daysun777  
1. Mditor 的哪个版本？
2. 什么浏览器？什么版本？

如何使用的？改变 Mditor 的大小有两种方式：
   
一、直接样式控制
```css
.mditor {
    width: 600px;
    height: 300px;
}
```

二、使用 Js API
```js
mditor.width = "600px";
mditor.height = "300px";
```
